"""Generate golden snapshots by running the predecessor's models (GRAND_PLAN.md §7).

**This is the only place the old repo is referenced.** Everything else in this package
compares against the files it writes, so the old code is a data source with one entrance,
not a dependency with many.

Run it deliberately, on the author's machine, when a golden should be (re)made::

    python -m gammaforge.validation.make_references                  # every scenario
    python -m gammaforge.validation.make_references --scenario baseline --model analytical

Configuration is environment-driven, because the old repo's location and its interpreter
are properties of a machine and not of this project:

* ``OLD_REPO`` — path to the predecessor checkout (default ``~/Work/Code/ComptonSuite``);
* ``OLD_REPO_PYTHON`` — the interpreter to run it under. It needs the old repo's own
  dependencies, notably scipy, which this repo deliberately does not have.

**Why a subprocess.** Both repos install a package named ``gammaforge``. One process
cannot hold both, so the old code runs in its own interpreter and communicates through
files. `_predecessor_driver` is the script that runs over there.

**What a golden is and is not.** The two repos' samplers are independent — this one draws
each variable from its own `numpy.random.SeedSequence` substream (§3.5), the old one drew
from a single stream — so the same nominal seed does *not* produce the same bunch. A
golden therefore carries Monte-Carlo noise of order ``1/sqrt(n_particles)`` relative to a
fresh run, and comparisons are made with a statistical tolerance (§7), never a tight one.
The scalars stored alongside are the exception: they are closed-form, both repos compute
them by independent code, and they should agree to near machine precision.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from ..io.laser import fit_gaussian_paraxial
from ..io.results import Axis, PhasespaceSlice, Results
from ..io.target import SLICE_AXES, OutputKind
from ..io.units import C_CGS, EV_CGS, scale_factor
from .golden import Provenance, save_golden
from .runners import derived_scalars
from .scenarios import SCENARIOS, Scenario, by_name

__all__ = ["MODELS", "make_references", "main"]

#: Models the predecessor can be asked for. All three are generated by default: the whole
#: bank takes about a minute on CPU, and a golden set with holes in it is a set nobody can
#: reason about. `delta` reuses xigma's Stage 0, so their agreement is expected rather than
#: independent evidence (§4.5) — it is snapshotted because the *normalization* question
#: §9.1 arbitrates is exactly what those two files record.
MODELS = ("analytical", "xigma", "delta")
DEFAULT_MODELS = MODELS

_DEFAULT_OLD_REPO = Path.home() / "Work" / "Code" / "ComptonSuite"

#: Old axis name -> this repo's `Axis`, and the factor taking the old repo's unit into
#: canonical CGS. The old repo baked units into axis names (``E_eV``) and worked in SI
#: elsewhere; both facts are recorded here once, at the boundary, and nowhere else.
_AXIS_TRANSLATION: dict[str, tuple[Axis, float]] = {
    "E_eV": (Axis.ENERGY, EV_CGS),
    "t_seconds": (Axis.TIME, 1.0),
    "x": (Axis.X, scale_factor("m", "cm")),
    "y": (Axis.Y, scale_factor("m", "cm")),
    "theta_x": (Axis.THETA_X, 1.0),
    "theta_y": (Axis.THETA_Y, 1.0),
}

#: Old `model_specific` key -> the canonical scalar name `runners.derived_scalars` uses.
_SCALAR_TRANSLATION = {
    "gamma0": "gamma0",
    "N_e": "n_electrons",
    "n_photons": "n_photons",
    "a0_interaction": "a0_peak",
}

#: Axis grouping -> `OutputKind`. The old repo identified a slice purely by its axis set;
#: this repo names the observable (§3.4), and `COLLIMATED_SPECTRUM` shares its axes with
#: `SPECTRAL_ANGULAR_DISTRIBUTION`, so the ambiguous grouping resolves to the uncollimated
#: one — which is what the old models produced.
_KIND_BY_AXES = {
    frozenset(axes): kind
    for kind, axes in SLICE_AXES.items()
    if axes is not None and kind is not OutputKind.COLLIMATED_SPECTRUM
}


def _scenario_payload(scenario: Scenario, n_energy_bins: int) -> dict:
    """Describe one scenario in the old repo's units (SI, eV) and field names."""
    beam, laser = scenario.beam, fit_gaussian_paraxial(scenario.laser)
    cm_to_m = scale_factor("cm", "m")
    return {
        "name": scenario.name,
        "n_particles": scenario.sampling.n_particles,
        "seed": scenario.sampling.seed,
        "n_energy_bins": n_energy_bins,
        "theta_col_rad": scenario.target.m("theta_x_col"),
        # xigma's Stage-1 table sizing knob. It is an engine parameter here (P5) and has no
        # place on a `Scenario`, but the old repo took it off its scenario object, so it is
        # supplied at this boundary — with headroom over the scenario's actual a0.
        "a0_max": max(0.5, 1.2 * laser.a0_peak()),
        "beam": {
            "bunch_charge_C": beam.m("bunch_charge") / scale_factor("C", "statC"),
            "kinetic_energy_eV": beam.m("kinetic_energy") / EV_CGS,
            "rel_energy_spread": beam.rel_energy_spread,
            "sigma_x_m": beam.m("sigma_x") * cm_to_m,
            "sigma_y_m": beam.m("sigma_y") * cm_to_m,
            "emit_geom_x_m": beam.m("emit_x") * cm_to_m,
            "emit_geom_y_m": beam.m("emit_y") * cm_to_m,
            "sigma_t_s": beam.m("sigma_z") / C_CGS,
        },
        "laser": {
            "pulse_energy_J": laser.m("pulse_energy") * scale_factor("erg", "J"),
            "wavelength_m": laser.m("wavelength") * cm_to_m,
            "sigma_x_m": laser.m("sigma_x") * cm_to_m,
            "sigma_y_m": laser.m("sigma_y") * cm_to_m,
            "duration_s": laser.m("duration"),
        },
    }


def _run_predecessor(payload: dict, repo: Path, python: str, work_dir: Path) -> dict:
    """Execute the driver under the old repo's interpreter; return its manifest."""
    payload_path = work_dir / "payload.json"
    payload_path.write_text(json.dumps(payload, indent=2))
    driver = Path(__file__).resolve().parent / "_predecessor_driver.py"

    environment = dict(os.environ)
    environment["PYTHONPATH"] = os.pathsep.join(
        [str(repo / "src")] + ([environment["PYTHONPATH"]] if environment.get("PYTHONPATH") else [])
    )
    completed = subprocess.run(
        [python, str(driver), str(payload_path)],
        cwd=str(repo), env=environment, capture_output=True, text=True,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"the predecessor driver failed (exit {completed.returncode}).\n"
            f"  repo:    {repo}\n  python:  {python}\n"
            f"--- stdout ---\n{completed.stdout}\n--- stderr ---\n{completed.stderr}"
        )
    return json.loads((work_dir / "manifest.json").read_text())


def _results_from_npz(path: Path) -> tuple[Results, dict[str, float]]:
    """Translate one driver output into this repo's `Results`, converting units.

    Densities are *per unit of each axis*, so rescaling an axis rescales the density by the
    inverse of the same factor — the step that turns ``dN/dE`` per eV into per erg. Getting
    this backwards would leave shapes identical and every yield wrong by ``1.6e-12``, which
    is exactly the kind of error a golden exists to catch, so it is done here, once.
    """
    with np.load(path, allow_pickle=False) as data:
        index = json.loads(str(data["index"]))
        raw_scalars = json.loads(str(data["scalars"]))
        slices = {}
        for entry in index:
            i = entry["index"]
            axes = {}
            density_factor = 1.0
            for name in entry["axes"]:
                axis, factor = _AXIS_TRANSLATION[name]
                axes[axis] = np.asarray(data[f"slice{i}_axis_{name}"]) * factor
                density_factor /= factor
            kind = _KIND_BY_AXES[frozenset(axes)]
            slices[kind] = PhasespaceSlice(
                axes=axes, distr=np.asarray(data[f"slice{i}_distr"]) * density_factor
            )

    scalars = {
        _SCALAR_TRANSLATION[key]: value
        for key, value in raw_scalars.items()
        if key in _SCALAR_TRANSLATION
    }
    return Results(photon_slices=slices), scalars


def make_references(
    scenarios=SCENARIOS,
    models=DEFAULT_MODELS,
    *,
    repo: Path | None = None,
    python: str | None = None,
    directory: Path | None = None,
    n_energy_bins: int = 256,
) -> list[Path]:
    """Run the predecessor over ``scenarios`` x ``models`` and write one golden each."""
    repo = Path(repo or os.environ.get("OLD_REPO") or _DEFAULT_OLD_REPO).expanduser()
    python = python or os.environ.get("OLD_REPO_PYTHON") or sys.executable
    if not (repo / "src" / "gammaforge").is_dir():
        raise FileNotFoundError(
            f"{repo} does not look like the predecessor checkout (no src/gammaforge). "
            f"Set OLD_REPO to point at it."
        )

    payload_scenarios = [_scenario_payload(scenario, n_energy_bins) for scenario in scenarios]
    written = []
    with tempfile.TemporaryDirectory(prefix="gammaforge-references-") as tmp:
        work_dir = Path(tmp)
        manifest = _run_predecessor(
            {"out_dir": str(work_dir), "repo": str(repo), "models": list(models),
             "scenarios": payload_scenarios},
            repo, python, work_dir,
        )
        for entry in manifest["entries"]:
            results, scalars = _results_from_npz(work_dir / entry["file"])
            provenance = Provenance(
                model=entry["model"],
                scenario=entry["scenario"],
                source_repo=str(repo),
                source_commit=manifest["commit"],
                source_dirty=bool(manifest["dirty"]),
                generated_utc=datetime.now(timezone.utc).isoformat(timespec="seconds"),
                note=f"predecessor {entry['model']} under python {manifest['python']}",
            )
            written.append(save_golden(results, provenance, scalars, directory))
    return written


def _check_scalars(scenarios) -> int:
    """Report each golden's scalars against what `io` computes now. Returns a failure count."""
    from .golden import available_goldens, load_golden

    failures = 0
    for scenario_name, model in available_goldens():
        scenario = by_name(scenario_name)
        if scenario not in tuple(scenarios):
            continue
        golden = load_golden(scenario_name, model)
        fresh = derived_scalars(scenario)
        for name, reference in sorted(golden.scalars.items()):
            error = abs(fresh[name] - reference) / abs(reference) if reference else abs(fresh[name])
            flag = "ok" if error <= 1e-6 else "MISMATCH"
            if error > 1e-6:
                failures += 1
            print(f"  {scenario_name}/{model} {name:<12} {fresh[name]:.12g} vs "
                  f"{reference:.12g}  ({error:.2e}) {flag}")
    return failures


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--scenario", action="append", dest="scenarios",
                        help="scenario name; repeatable (default: all)")
    parser.add_argument("--model", action="append", dest="models", choices=MODELS,
                        help=f"predecessor model; repeatable (default: {list(DEFAULT_MODELS)})")
    parser.add_argument("--repo", type=Path, help="predecessor checkout (or set OLD_REPO)")
    parser.add_argument("--python", help="interpreter for it (or set OLD_REPO_PYTHON)")
    parser.add_argument("--bins", type=int, default=256, help="energy bins per spectrum")
    arguments = parser.parse_args(argv)

    scenarios = [by_name(name) for name in arguments.scenarios] if arguments.scenarios else SCENARIOS
    written = make_references(
        scenarios, tuple(arguments.models or DEFAULT_MODELS),
        repo=arguments.repo, python=arguments.python, n_energy_bins=arguments.bins,
    )
    for path in written:
        print(f"wrote {path}")
    print("scalar cross-check against this repo's own closed forms:")
    return 1 if _check_scalars(scenarios) else 0


if __name__ == "__main__":
    raise SystemExit(main())
